name: commit-build-tui

permissions:
  contents: write

on:
  push:

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [cpython-3.13]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python with uv
        run: uv python install ${{ matrix.python }}

      - name: Create venv
        run: uv venv

      - name: Install project dependencies with uv
        run: uv sync --extra tui --extra build

      - name: Build executable with pyinstaller
        run: uv run pyinstaller launch_tui.spec

      - name: Upload exe artifact (Windows)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: positive_password_book_launch_tui.exe
          path: dist/*

      - name: Upload exe artifact (Linux)
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: positive_password_book_launch_tui
          path: dist/*

      - name: Get package version (Linux)
        id: get_version_linux
        if: runner.os == 'Linux'
        run: |
          version=$(uv run ci/get_version.py)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get package version (Winodws)
        id: get_version_windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd ci
          uv venv --python cpython-3.13
          $version = uv run get_version.py
          echo "Version: $version"
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Find built exe (Linux)
        id: find_exe_linux
        if: runner.os == 'Linux'
        run: |
          file=$(ls dist/positive_password_book_launch_* | head -n 1)
          echo "exe_path=$file" >> $GITHUB_OUTPUT
          echo "exe_name=$(basename \"$file\")" >> $GITHUB_OUTPUT

      - name: Find built exe (Windows)
        id: find_exe_windows
        if: runner.os == 'Windows'
        run: |
          $file = uv run find_exe.py
          echo "exe_path=$file" >> $env:GITHUB_OUTPUT
          echo "exe_name=$(uv run python -c "import os; print(os.path.basename('$file'))")" >> $env:GITHUB_OUTPUT

      - name: Show dist contents (debug)
        shell: bash
        run: |
          echo "PWD: $(pwd)"
          ls -la dist || true

      - name: Get short SHA (Linux)
        id: get_sha
        if: runner.os == 'Linux'
        run: |
          short=$(uv run ci/get_sha.py $GITHUB_SHA)
          echo "short_sha=$short" >> $GITHUB_OUTPUT

      - name: Get short SHA (Windows)
        id: get_sha
        if: runner.os == 'Windows'
        run: |
          $short = uv run ci/get_sha.py $GITHUB_SHA
          echo "short_sha=$short" >> $env:GITHUB_OUTPUT

      - name: Rename exe to include version (Linux)
        id: rename_exe_linux
        if: runner.os == 'Linux'
        env:
          ORIG: ${{ steps.find_exe.outputs.exe_path }}
          VER: ${{ steps.get_version_linux.outputs.version }}
        run: |
          exe_path=$(python ci/rename_exe.py $ORIG $VER)
          echo "exe_path=$exe_path" >> $GITHUB_OUTPUT

      - name: Rename exe to include version (Windows)
        id: rename_exe_windows
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          ORIG: ${{ steps.find_exe.outputs.exe_path }}
          VER: ${{ steps.get_version_windows.outputs.version }}
        run: |
          cd ci
          uv venv --python cpython-3.13
          $exe_path = uv run python ci/rename_exe.py $ORIG $VER
          exho "exe_path=$exe_path" >> $GITHUB_OUTPUT
          cd ..

      - name: Get datetime
        id: get_datetime
        run: |
          datetime=$(python -c "import datetime; print(datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))")
          echo "datetime=$datetime" >> $GITHUB_OUTPUT

      - name: Create prerelease and upload wheel (Linux)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version_linux.outputs.version }}-pre-${{ steps.get_sha.outputs.short_sha }}-${{ steps.get_datetime.outputs.datetime }}__${{ matrix.os }}
          name: pre-release+${{ steps.get_version_linux.outputs.version }}+${{ steps.get_sha.outputs.short_sha }}+${{ matrix.python }}+${{ steps.get_datetime.outputs.datetime }}__${{ matrix.os }}
          prerelease: true
          artifacts: ${{ steps.rename_exe_linux.outputs.exe_path }}
          body: |
            **這是測試版，使用github action製作**
            - 系統： ${{ matrix.os }}
            - 版本： ${{ steps.get_version_linux.outputs.version }}
            - 時間： ${{ steps.get_datetime.outputs.datetime }}
            - github_sha： ${{ steps.get_sha.outputs.short_sha }}

      - name: Create prerelease and upload wheel (Windows)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version_windows.outputs.version }}-pre-${{ steps.get_sha.outputs.short_sha }}-${{ steps.get_datetime.outputs.datetime }}__${{ matrix.os }}
          name: pre-release+${{ steps.get_version_windows.outputs.version }}+${{ steps.get_sha.outputs.short_sha }}+${{ matrix.python }}+${{ steps.get_datetime.outputs.datetime }}__${{ matrix.os }}
          prerelease: true
          artifacts: ${{ steps.rename_exe_windows.outputs.exe_path }}
          body: |
            **這是測試版，使用github action製作**
            - 系統： ${{ matrix.os }}
            - 版本： ${{ steps.get_version_windows.outputs.version }}
            - 時間： ${{ steps.get_datetime.outputs.datetime }}
            - github_sha： ${{ steps.get_sha.outputs.short_sha }}
